export const CONFIG = {
  PRESET_NAMES: [
    'Vector Sphere',
    'Mutant Torus',
    'Lissajous Knot',
    'Plasma Field',
    'Fractal Spiral',
    'Hyperbolic Paraboloid',
    'Nebula Vortex',
    'Chaos Ribbon',
    'Quantum String',
    'Galactic Web',
    'Voxel Grid',
    'Morphing Cube',
    'Heart Pulse',
    'Black Hole Singularity',
    'Tesseract Fold',
    'Hyperspace Jump',
    'Wormhole Bridge',
    'Supernova Remnant',
    'Andromeda Spiral',
    'Gamma-Ray Pulsar',
    'Peyote',
    'Hyperspace',
    'Mycelia',
    'Recursion',
    'K-Hole',
    'Erdős Lattice',
  ],
  SPECTRAL_PALETTE: [
    '#08120A', '#18BF34', '#B8E61F', '#FFB11A',
    '#FF6D0A', '#FF1F1F', '#B30000', '#2A0000'
  ],
  WHITE_POINT: '#FFFFFF',
  SINGLE_CORE_MODE: true,
  WORMHOLE_MODE: true,
  SHOW_WAVEFORM: false,
  SHOW_SPARK_RING: false,
  AUTO_PRESET_MUTATION: true,
  ENVIRONMENT_MODE: true,
  GLITCH_PROFILE: 'aggressive' as const,
  MASHUP_INTERVAL_MS: 15_000,
  MASHUP_DYNAMIC_MODE: true,
  MASHUP_DYNAMIC_AUTO_WITHOUT_TOGGLE: true,
  MASHUP_DYNAMIC_SCORE_THRESHOLD: 0.58,
  MASHUP_DYNAMIC_HYSTERESIS: 0.12,
  MASHUP_DYNAMIC_BASE_COOLDOWN_MS: 2_200,
  MASHUP_DYNAMIC_MAX_COOLDOWN_MS: 6_800,
  MASHUP_DYNAMIC_BEAT_LOCK: true,
  MASHUP_DYNAMIC_IDLE_FORCE_MS: 18_000,
  MASHUP_DYNAMIC_IDLE_MIN_SCORE: 0.36,
  MASHUP_DYNAMIC_IDLE_MIN_PULSE: 0.5,
  MASHUP_DYNAMIC_VOLATILITY_WINDOW_FRAMES: 120,
  ROBUST_NORMALIZATION_WINDOW_FRAMES: 180,
  MASHUP_PREDICTION_HORIZON_SEC: 0.6,
  MASHUP_MACRO_HORIZON_SEC: 6.0,
  RUST_LOOKAHEAD_ENABLED: true,
  RUST_ABSOLUTE_LOOKAHEAD_ENABLED: true,
  RUST_ABSOLUTE_LOOKAHEAD_FPS: 48,
  RUST_ABSOLUTE_LOOKAHEAD_WINDOW_SEC: 0.09,
  MASHUP_RUST_ANALYSIS_MIN_READINESS: 0.32,
  MASHUP_BASS_SUSTAIN_LOCK: true,
  MASHUP_BASS_SUSTAIN_THRESHOLD: 0.62,
  MASHUP_BASS_SUSTAIN_MIN_RATIO: 0.58,
  MASHUP_BASS_SUSTAIN_HORIZON_SEC: 2.4,
  MASHUP_TRANSITION_TARGET_MS: 1_000,
  MASHUP_DROP_SYNC_MODE: true,
  MASHUP_DROP_SYNC_MIN_LIKELIHOOD: 0.64,
  MASHUP_DROP_SYNC_MIN_SCORE: 0.48,
  MASHUP_DROP_SYNC_REARM_MS: 1_400,
  DEFAULT_TRACK_NAME: 'No track loaded — drag a file or click FILE',
};
